### ISSUE TITLE
Suppress PlotBelowHorizonWarning messages in Sphinx build

### ISSUE THREAD

**Issue by cdeil** [astropy/astroplan#100]
So far we had a clean (warning-free) Sphinx build, but since yesterday we have a bunch of:
```
WARNING: PlotBelowHorizonWarning: Target "Algol" is below the horizon at time: 2457235.75 [astroplan.plots.sky]
```
Full log: https://gist.github.com/cdeil/570c00c055a414b095a9

Personally I don't like packages that emit warnings for things that occur all the time in normal usage and would remove the warnings here. But I think others like to have them in?

If so, could someone please suppress the warnings in the Sphinx build?

**Comment by bmorris3** [comment]
@cdeil Does this simply require catching the warnings in the code that generates the sphinx plots, i.e. with `warnings.simplefilter("ignore")`?

**Comment by cdeil** [comment]
Does the warning occur in "normal usage" even in cases where one gets a correct output plot?
If so, that's not OK, let's fix this by removing the warning.

But to answer your question: yes, you can filter out warnings in the Sphinx build. (but it's not a good idea, our code and examples should be correct, i.e. there shouldn't be a warning that needs filtering).

**Comment by bmorris3** [comment]
In normal usage, you should only be plotting positions of things above the horizon. If the user tries to plot the position of a target that isn't above the horizon, nothing will be plotted -- that's when the warning is raised, to show the user that nothing is being plotted because there's nothing to plot. I think the examples have instances where shortcuts are being used to make plots that generate targets below the horizon, so I'll filter them out in the sphinx build.

**Comment by cdeil** [comment]
> In normal usage, you should only be plotting positions of things above the horizon.

That means extra work for the user. Before calling plot, always write some code to select just the targets above the horizon. It's much more convenient to just plot all and have those below the horizon not show up. I've never gotten a warning from matplotlib that I'm plotting something outside limits, it's just silently ignored, which is the behaviour I'd prefer here also.

**Comment by bmorris3** [comment]
@eteq / @jberlanga -- any objections to turning off the warnings in plots by default? See @cdeil's comments above.

**Comment by ejeschke** [comment]
I think it makes sense to have the default be no warnings, but it would be nice to have the option to get the warnings.

**Comment by bmorris3** [comment]
It'd be great to hear from @eteq and @jberlanga before merging #124 so I can feel out whether or not to sneak suppressing this warning into that PR.

**Comment by jberlanga** [comment]
>Before calling plot, always write some code to select just the targets above the horizon.

@cdeil : Do you mean the user should do this or we should be doing this for the user?  

Over the summer, @eteq and I discussed the idea of throwing out the times (& thus corresponding alt/az coordinates to plot) corresponding to an object being below the horizon.  I don't remember the exact reason why we thought it was a bad idea at the time.  

For me at least, without the warnings (or some extra info on the plot itself), the skyplot can be misleading since we don't timestamp the chronologically first/last visible position of each object.  Since each object's positions are plotted independent of all other objects, and of course each rises/sets independently as well, you can't a priori guarantee that you are seeing all objects during the exact same time window (unless you've done this legwork outside the use of `plot_sky`).  This was my reasoning behind the warnings.  There's only so much you can do to discourage naive usage/interpretation of the plotting functions and their output, but all the same, I agree with @ejeschke that having the option of being warned in some way (e.g., `warnings_on=False` by default) would be fantastic.

**Comment by cdeil** [comment]
>> Before calling plot, always write some code to select just the targets above the horizon.

> @cdeil : Do you mean the user should do this or we should be doing this for the user?

I think documenting how to do this selection / advertising users add this to their scripts is a bit tedious, no?

@bmorris3 – Can you make a PR with your preferred solution to force a decision on this issue?

I think the options are:

1. Remove `PlotBelowHorizonWarning`
2. Suppress `PlotBelowHorizonWarning` in each docs example that currently plots targets below the horizon.
3. Select only targets above horizon in each docs example that currently plots targets below the horizon.
4. Suppress `PlotBelowHorizonWarning` globally in `docs/conf.py`

Maybe I missed some ...?

FYI: My preference would be 1., I'm OK with 2. and 3., and I think 4. is not OK (because then users will get the warning, but we don't explain to them why in the docs and even "cheat" ourselves to get rid of the annoying warnings with some global, unseen setup code.

**Comment by bmorris3** [comment]
In 429350a, I've taken the option based on @ejeschke and @jberlanga's suggestion. I've turned the warning off by default, but there's a keyword argument `warn_below_horizon` which can be set to `True` to raise warnings which someone somewhere might find useful. This way no warnings are raised when building the docs, and the warning isn't fully removed for users who might like it. 

If that's sufficient @cdeil, we're good to merge #124 when the tests pass and to close this issue.

**Comment by cdeil** [comment]
:+1:

**Comment by bmorris3** [comment]
@cdeil Tests are passing, I'm merging and closing this issue.
