### ISSUE TITLE
Redraw figures for interactive sessions by default?

### ISSUE THREAD

**Issue by bmorris3** [astropy/astroplan#128]
In #115 @cdeil [called into question](https://github.com/astropy/astroplan/pull/115#discussion_r40576627) the standard practice in `astroplan.plots` of calling `ax.figure.canvas.draw()` (for example, [see here](https://github.com/astropy/astroplan/blob/master/astroplan/plots/sky.py#L210)) to redraw figures for interactive sessions.

Can maybe @adrn or @eteq clarify what that line does for @cdeil ?

**Comment by eteq** [comment]
@bmorris3 @cdeil - the key reason for the use of draw is to mimic the pyplot library (and most other plotting add-ons that use matplotlib), which does a `draw` call at the end of any user-interaction function.  For matplotlib <1.5, this is necessary because the OO interface (``ax.<whatever<``) does *not* do any `draw` calls - it's left to the user to do that.  So as long as only the OO interface is used, there is not a "double-draw" - it only happens the one time, which is the desired behavior.  Given that these are mostly meant as "quick-look" plotting functions I think worrying about performance like that probably is not too critical.

However, in mpl 1.5 and on (based on that link @cdeil mentioned in the other thread), it looks like there's some real neat new machinery that keeps track of whether or not a draw is necessary.  So  maybe the thing to do is something like this:

```
if not hasattr(ax.figure, 'stale'):
    ax.figure.canvas.draw()
```

because that `stale` attribute seems to be the new thing added in 1.5 that's used internally to decide if something needs redrawing or not.  So that's sort of a duck-typing version of asking if we're at v1.5 or later.

**Comment by jberlanga** [comment]
@eteq @bmorris3 @cdeil  So is the consensus to replace calls to `ax.figure.canvas.draw()` with a check like the one mentioned above?

**Comment by cdeil** [comment]
> the key reason for the use of draw is to mimic the pyplot library (and most other plotting add-ons that use matplotlib), which does a draw call at the end of any user-interaction function. 

Is this true?
I don't see a `draw` call in the pyplot functions or (to pick one popular example of a plotting library built on top of matplotlib) in seaborn:
https://github.com/matplotlib/matplotlib/blob/master/lib/matplotlib/pyplot.py#L2680
https://github.com/mwaskom/seaborn/blob/master/seaborn/distributions.py#L606

So to mimic what other high-level plot functions built on top of matplot are doing, we should *not* call draw, no?

Or am I misreading the code / behaviour of pyplot / seaborn?
