### ISSUE TITLE
Where are the alt, az attributes documented?

### ISSUE THREAD

**Issue by bmorris3** [astropy/astroplan#131]
I've been getting lots of tips on holes in documentation from @tobyrsmith, thanks Toby!

`SkyCoord`s in the `AltAz` frame, like those returned by `Observer.altaz`, have an `alt` and `az` attribute which you know can be accessed like this: 

``` python
from astroplan import FixedTarget, Observer
apo = Observer.at_site('apo')
vega = FixedTarget.from_name('vega')
from astropy.time import Time
aa = apo.altaz(Time.now(), vega)
aa.alt
aa.alt.degree
aa.alt.hourangle
```

This isn't explicitly mentioned in the [`Observer.altaz` docs](http://astroplan.readthedocs.org/en/latest/api/astroplan.Observer.html?highlight=altaz#astroplan.Observer.altaz) or the astropy [`AltAz` docs](http://docs.astropy.org/en/stable/api/astropy.coordinates.AltAz.html#astropy.coordinates.AltAz). The nearest I found in the astropy docs is the ["observation example"](http://docs.astropy.org/en/stable/coordinates/observing-example.html) which isn't very expository. 

@eteq - Should there be `alt` and `az` properties of `AltAz` in the astropy documentation? If not, I'd like to add a few lines to the docstring examples in astroplan to make it clear how to do so.

**Comment by eteq** [comment]
Hmm, this is a good point.  The way you're "supposed" to figure it out is that the documentation says in a few places that `SkyCoord` gets names from the frames, the `AltAz` documentation shows that `alt` and `az` are input parameters, and it also says somewhere that the inputs are the same as the attribute names.  But you're absolutely right that this is a twisted chain of logic that's not at all obvious from the docs.

Now for possible solutions: the first place I would think is to try to convince the [documentation for AltAz](http://docs.astropy.org/en/stable/api/astropy.coordinates.AltAz.html#astropy.coordinates.AltAz) to show `alt` and `az` (and `distance`) in the "Attributes Summary" section.  It's not doing that right now because of some subtleties in how the classes are implemented, but it probably could be made to work with a bit of hacking.  @bmorris3 and @tobyrsmith : do you think this would be sufficient to figure it out?  Or would seeing that those are attribute names on the summary list still not have made it clear that this is what you need to do?

Another piece that might help is astropy/astropy-tutorials#97 - that's not in yet, but it does include a few examples that clearly show the ``.alt`` and ``.az`` usage.  (On a related note, that tutorial desperately needs a *non*-expert to review it and give feedback on what might need more clarification.   @tobyrsmith, do you think you might be able to do so?)

**Comment by jberlanga** [comment]
:+1: on clarifying this in the astropy docs, but also adding a note somewhere in ours.  From experience this summer, I agree that it was not at all obvious where `alt` and `az` were coming from to someone new to `astropy.coordinates`--I had to dig through @bmorris3's code to find out where he was getting these quantities.

**Comment by bmorris3** [comment]
Suggestion from @eteq: let's make an example in the astroplan `observer.altaz` docstring that shows that the returned sky coordinate in the `AltAz` frame has a `.alt` and `.az` property/attribute.

**Comment by bmorris3** [comment]
Following up on this old issue. As of astropy v3.2.3 the astropy docs don't specify that `alt` and `az` are attributes of `AltAz` objects.

**Comment by bmorris3** [comment]
Moving discussion to astropy/astropy#9548
