### ISSUE TITLE
constraints cannot be applied to a single target

### ISSUE THREAD

**Issue by eteq** [astropy/astroplan#134]
I noticed the following surprising behavior:

```
>>> obs = astroplan.Observer.at_site('Palomar')
>>> targ = astroplan.FixedTarget.from_name('Albireo')
>>> t = Time('J2000')
>>> c = astroplan.AirmassConstraint(2)
>>> c(obs,[targ],t)
array([[ True]], dtype=bool)
>>> c(obs,targ,t)
TypeError: 'FixedTarget' object is not iterable
```

Is this intended?  I would have expected constraints to give a 1D array if either the target or time passed in is a scalar (or a scalar output if _both_ are scalar).  

cc @bmorris3

**Comment by bmorris3** [comment]
The module will force scalar inputs to non-scalars because the logical operators are applied along axes that otherwise wouldn't exist, [see here for example](https://github.com/astropy/astroplan/blob/master/astroplan/constraints.py#L623-L625). 

One solution could be to simply add an extra statement before returning the outputs to scalarize the output arrays if the inputs are scalar.

**Comment by eteq** [comment]
Gotcha, that makes sense - I like the solution of picking the dimension at the end based on the inputs.  I.e.
```
if input_is_scalar:
    return output.ravel()[0]
elif input_had_scalar_time:
    return output[0]
elif input_had_scalar_target:
    return output[:, 0]
else:
    return output
```
is basically what you mean, right?

**Comment by bmorris3** [comment]
Yes that's what I mean. Hopefully I can implement this soon. Reception of astroplan at dotastro has been pretty good, so I hope I can work on these things soon! Maybe I'll see if I can get this particular fix done now...
