### ISSUE TITLE
Boolean combination of constraints

### ISSUE THREAD

**Issue by astrofrog** [astropy/astroplan#135]
I don't use astroplan, but while watching @bmorris3's demo at #dotastro, I thought it would be cool to be able to combine constraints with boolean operators:

```
(constraint1 & constraint2) | constraint3
```

**Comment by bmorris3** [comment]
That's what's happening slightly under the hood, but you can definitely do this from above the hood. Check out the [source here](https://github.com/astropy/astroplan/blob/master/astroplan/constraints.py#L520-L565) to see how that's being done.

In short, we're doing this under the hood: 
```python
    applied_constraints = [constraint(observer, targets, times) for constraint in constraints]
    contraint_arr = np.logical_and.reduce(applied_constraints)
```

**Comment by eteq** [comment]
@astrofrog - so you mean you want to boolean together the constraint *objects*, rather than the result of applying the constraints, is that right?

**Comment by bmorris3** [comment]
If that is right, I've written a little tutorial on how to do this which you can [view here](http://nbviewer.ipython.org/github/bmorris3/gsoc2015/blob/master/constraints_boolean_logic.ipynb). Is that a clear demonstration, @astrofrog? @eteq – should I add this to the tutorials on RTD?

**Comment by astrofrog** [comment]
Looks good!

**Comment by bmorris3** [comment]
@astrofrog – since you brought it up, can you think of a situation where it would be useful to compute something like this? I could include a mini tutorial in the docs but I'd like to use a non-trivial example. 

One example could be: let's say we want to observe a target with one of two telescopes at different observatories. You can compute whether or not the target is observable at one observatory *or* the other by computing the constraints on each and combining with an `|`.

**Comment by astrofrog** [comment]
I haven't looked at what constraints are available, but I could imagine saying e.g  that I want it to be either visible below an air mass of 1.5  for 1 hour at least, or below an air mass of 3 for 4 hours at least. I'm not an observer, so just making stuff up :)

**Comment by bmorris3** [comment]
Since this question has been answered, I'll close this issue.
