### ISSUE TITLE
Revise tests that use pyephem

### ISSUE THREAD

**Issue by bsipocz** [astropy/astroplan#199]
pyephem has been removed from the travis dependencies, however still a few tests use it. Though for some weird reason they are not failing.

- [ ] Revise tests to make sure they fail when there is no pyephem installed
- [ ] remove unneccessary tests if any, e.g. remove or move the ``print_pyemphem_...`` ones to a separate file, they are very confusing at their current place as pytest does nothing with them?
- [ ] Add back pyephem as test dependency to docs and CI

**Comment by bmorris3** [comment]
The `print_pyephem_*` functions are still there (and were always there) because they are used to calculate the values that we test against. For instance, we can compare the alt/az of a target with PyEphem as an independent check on astroplan, and those functions are used to produce the hard-coded numbers that are in the tests themselves. That way you can run the tests without pyephem, and you can see how we got the numbers hard-coded into those tests if you have PyEphem by running the `print_pyephem_*` functions. 

Are there tests left that require PyEphem?

**Comment by bsipocz** [comment]
> Are there tests left that require PyEphem?

I think any test that does ``import ephem`` needs pyephem to be installed, don't they?

**Comment by bmorris3** [comment]
None of the tests import ephem, only the `print_pypehem_*` functions, which are not executed when testing. They need to be called manually by a user.

**Comment by bsipocz** [comment]
Ahh, ok indeed. Sorry for the noise.
