### ISSUE TITLE
problem with galaxy rise time for 2017-03-01

### ISSUE THREAD

**Issue by aakepley** [astropy/astroplan#276]
I'm trying to figure out the rise/set times for a bunch of sources at the GBT and think I have found a bug in the rise/set time for a particular source for the date 2017-03-01. When I select the date 2017-03-04, I get the following times:

- Rise:  2017-03-04 05:19:03.776147
- Transit: 2017-03-04 06:33:16.235763
- Set:  2017-03-04 07:47:30.688286

However, when I select the date 2017-03-01, I get the following times:

- Rise: 2017-03-02 05:26:58.095280
- Transit:  2017-03-01 06:45:03.964774
- Set:  2017-03-01 07:59:15.481768

I believe that the date on the rise time should be 2017-03-01, NOT 2017-03-02 (to match the results on 03-04). Changing to previous and next rise times doesn't help:
- Previous:2017-02-28 05:34:48.990694
- Next: 2017-03-02 05:26:58.095280

This only happens with one relatively low declination source (-18deg). All my other source rise/set times look good.

I've put test code below showing the issue.

```
from astroplan import Observer, FixedTarget
from astroplan.plots import plot_airmass

from astropy.coordinates import SkyCoord, EarthLocation
from astropy.time import Time
from astropy.table import Table
import astropy.units as u


# setup observing
location = EarthLocation.from_geodetic(lon='-79d50m23.406s',lat='38d25m59.236')
gbt = Observer(location=location, elevation=807.43*u.m,name='gbt',timezone='US/Eastern')
time = gbt.midnight(Time('2017-03-04 5:00:00'))

coordinates = SkyCoord(180.47086*u.deg, -18.867990*u.deg, frame='fk5')
galaxy = FixedTarget(name='NGC4038', coord=coordinates)

galaxy_rise = gbt.target_rise_time(time, galaxy,horizon=30*u.deg)
galaxy_transit = gbt.target_meridian_transit_time(time,galaxy)
galaxy_set = gbt.target_set_time(time, galaxy,horizon=30*u.deg)


print galaxy_rise.datetime
# 2017-03-04 05:19:03.776147
print galaxy_transit.datetime
# 2017-03-04 06:33:16.235763
print galaxy_set.datetime
# 2017-03-04 07:47:30.688286


time = gbt.midnight(Time('2017-03-01 5:00:00'))
galaxy_rise = gbt.target_rise_time(time, galaxy,horizon=30*u.deg)
galaxy_transit = gbt.target_meridian_transit_time(time,galaxy)
galaxy_set = gbt.target_set_time(time, galaxy,horizon=30*u.deg)

print galaxy_rise.datetime
# 2017-03-02 05:26:58.095280
print galaxy_transit.datetime
# 2017-03-01 06:45:03.964774
print galaxy_set.datetime
# 2017-03-01 07:59:15.481768

galaxy_rise_prev = gbt.target_rise_time(time, galaxy,horizon=30*u.deg,which='previous')
galaxy_rise_next = gbt.target_rise_time(time, galaxy,horizon=30*u.deg,which='next')

print galaxy_rise_prev.datetime
# 2017-02-28 05:34:48.990694
print galaxy_rise_next.datetime
# 2017-03-02 05:26:58.095280
```

**Comment by wtgee** [comment]
Hi @aakepley. It looks like from that location (South Pole?) NGC 4038 doesn't go above 30 degrees on that date. It just skirts it at 29 degrees and then the next day goes back above 30. Changing your horizon to 29 degrees will give you the correct answer:

```
time = gbt.midnight(Time('2017-03-01 5:00:00'))
galaxy_rise = gbt.target_rise_time(time, galaxy,horizon=29*u.deg)
galaxy_transit = gbt.target_meridian_transit_time(time,galaxy)
galaxy_set = gbt.target_set_time(time, galaxy,horizon=30*u.deg)

print(galaxy_rise.datetime)
# 2017-03-01 05:17:22.505081
print(galaxy_transit.datetime)
# 2017-03-01 06:45:03.962682
print(galaxy_set.datetime)
# 2017-03-01 07:59:15.483498
```

**Comment by aakepley** [comment]
Hi @wtgee  -- The GBT is in West Virginia (lat=~38.5). What physical effect is causing this difference? If it's refraction, why would it be different on one day from a day 3 days later?

**Comment by wtgee** [comment]
Sorry @aakepley, you are quite right that the galaxy goes up to 32.5 degrees and I think you are also right that you found a subtle bug.

In `Observer._calc_riseset` a 24 hour time grid is created which is then passed to `Observer._horiz_cross` to get the time when the target crosses the horizon. For your target, this happens twice in a 24 hour period. `_horiz_cross` successfully finds these two times (here: https://github.com/astropy/astroplan/blob/master/astroplan/observer.py#L559) but slightly later it only grabs the first index for a given target, assuming there will only be one (here: https://github.com/astropy/astroplan/blob/master/astroplan/observer.py#L593).

@bmorris3 might want to chime in on a possible solution to that. It seems like the logic on line 593 would need to incorporate whether it was rising or setting and which (nearest, next, previous) you wanted in order to determine whether you wanted the first or last occurrence within the 24 hour period. If line 593 adds all of them then `_horiz_cross` will happily return the time and altitude limits back to `_calc_riseset` which could figure out that logic.

**Comment by bmorris3** [comment]
Hi @aakepley! I'm trying to sort through this issue. Do you think it's related to these other ones, #261 #155, and the caveats noted in the [astroplan FAQ](http://astroplan.readthedocs.io/en/latest/faq/precision.html)? Our rise/set approximations are known to fail in some corner cases.

**Comment by aakepley** [comment]
It doesn't seem to be directly related to these issues. The most closely associated one is #155 (the midnight within 30s of input time). The galaxy rise time is within ~30s of midnight. See code below:

```
galaxy_rise_prev = gbt.target_rise_time(time, galaxy,horizon=30*u.deg,which='previous')
galaxy_rise_next = gbt.target_rise_time(time, galaxy,horizon=30*u.deg,which='next')

print galaxy_rise_prev.datetime
# 2017-02-28 05:34:48.990694
print galaxy_rise_next.datetime
# 2017-03-02 05:26:58.095280

# estimating the rise time on 2017-03-01
time_diff =  galaxy_rise_next - galaxy_rise_prev
bet_time = galaxy_rise_prev + time_diff/2.0

print gbt.altaz(bet_time,galaxy).alt
# 30d00m33.5923s
# so az looks okay on date (>30deg). 

# rise time on 3-01
bet_time.iso
# '2017-03-01 05:30:53.537'

# midnight (see earlier test case for code).
time.iso
# '2017-03-01 05:31:31.350'

mid_diff = bet_time - time
mid_diff.sec
# -37.81329318881035

# galaxy rise time is close to midnight.

```

**Comment by eteq** [comment]
@aakepley - can you give the version of python, numpy, and astroplan you were seeing this with?  I think I agree with https://github.com/astropy/astroplan/issues/276#issuecomment-269834425 that this is a bug due to subtle violations of expectations in the algorithm... but to do a fix I need to be able to reproduce, and when I do it (python 3.6, numpy 14.2, astropy 3.0, and astroplan 0.4), I get the right answer (i.e. 3/1 and 3/2 instead of 2/28 and 3/2)

**Comment by aakepley** [comment]
@eteq -- Unfortunately, I think this information is lost to the mists of time. I didn't report them when I first reported the issue  like a good tester should, either. boo. I've also completely changed computers between then and now... For what it's worth, I also now get the correct values with python 2.7.13, numpy 1.12.1, astropy 1.3.2., astroplan 0.2.1.

**Comment by eteq** [comment]
Ok, thanks @aakepley - I think we'll consider this closed unless the problem comes back or @wtgee can reroduce (in which case feel free to reopen!)
