### ISSUE TITLE
User defined Target properties lost

### ISSUE THREAD

**Issue by rodleiva** [astropy/astroplan#357]
Hi,

I'm trying to define a new class of target based on FixedTarget with extra properties to be used by a User-defined Constraint. This could be Magnitude, last-time observed, etc.

Unfortunately, in several places the target is transformed in a "target" which is no more than a astropy.SkyCoord, then all extra properties are discarded and make a pain in the neck to program any user-defined Constraint.

This is done in the method __call__ in the class Constraint. 

Any idea how to deal with that?

**Comment by jdgibson** [comment]
I ran into the same issue.  Rather than trying to subclass FixedTarget as a new target class with extra properties, an approach is to use your new user-defined constraint strictly as a block-specific constraint, rather than a global constraint.  You can then pass in your extra properties to the user-defined constraint on an observing block-by-block basis.  The math works out the same for global and block constraints when observing block scores are calculated.  Hope this helps.

**Comment by rodleiva** [comment]
Thanks,
That was a good solution. I just created a user-defined constraint which uses a user-defined parameter.
