### ISSUE TITLE
Priority scheduler leaves a lot of empty time

### ISSUE THREAD

**Issue by jkampars** [astropy/astroplan#397]
Firstly, i got this plot by copy and pasting plot_schedule_airmass() function and changing the plot_airmass() function to plot_altitude(). 
![figure_1](https://user-images.githubusercontent.com/40435128/50689211-58c10f00-1031-11e9-8dfb-69b2d369fe2c.png)
The red dashed lines are the altitude constraints i have, and those are the only constraints for this scheduler. Logically, you would just start observing at 7:00, observe every target and stop, but the priority scheduler decides to spread them out to concentrate them at certain points, mostly the start, middle and end of the given time window. I tried looking into the code of priority_scheduler and scorer but i can't wrap my head around it.

**Comment by bmorris3** [comment]
Hi @jkampars! The priority scheduler tries to schedule each observing block (OB) in order of priority. The top priority target gets scheduled at its optimal time, then the next target get scheduled closest to its optimal time, and so on. If you attach a list of the priorities for each of your targets, that might help explain the behavior you're seeing.

**Comment by jkampars** [comment]
Is there a way to override the scheduler, so it doesn't care about what altitude the target is at as long as it is inside the constraints, without having to make a custom scheduler or scorer? Does the scorer decide that targets should be observed at maximum altitude or the scheduler itself? The scorer returns a boolean so i didn't think that's where this error happens.  
Here is the list of priorities for these targets:
w75s - 4
dr21 - 2
l1287 - 1
laha234 - 4
oh43p8 - 4
g37p479 - 4
g50p03 - 3
on1 - 2
g43p79 - 2
g107p3 - 3
g59p783 - 4
g136p84 - 2
g30p99 - 2
w3oh - 4
ngc7538 - 3
g85p41 - 2

**Comment by T0T4R4** [comment]
@jkampars did you end up solving this issue ?

**Comment by michaelbaisch** [comment]
I think I ran into a similar problem and I think I figured out what the problem ist. I believe the problem is [here](https://github.com/astropy/astroplan/blob/main/astroplan/scheduling.py#L789) with `np.argsort`. When using `boolean_constraint=True` there are many equal values in the `sum_scores` array. And argsort without any explicit `kind` argument uses quicksort where equal values have no specific order.

To improve the ordering you could use:
```python
for idx in np.argsort(sum_scores, kind='mergesort')[::-1]:
```
then your schedule will be filled from the back. So we want to negate before sorting:

```python
for idx in np.argsort(-sum_scores, kind='mergesort'):
```

Now I think it should work.
