### ISSUE TITLE
Provide succinct way to get time object in the observer's time zone

### ISSUE THREAD

**Issue by ejeschke** [astropy/astroplan#46]
Currently, if I want to get a local time for working with `astroplan`, I have to write a somewhat verbose bit of code:
```python
# Get times for 00:30 and 02:35 in my timezone on July 28, 2015 that I can use with astroplan
t_start = observer.datetime_to_astropy_time(datetime.datetime(2015, 07, 28, 0, 30, 0)) 
t_stop = observer.datetime_to_astropy_time(datetime.datetime(2015, 07, 28, 2, 35, 0)) 
```
(this works because the naive datetime is localized with the observer's timezone in `datetime_to_astropy_time`).

However, it would be extremely convenient to be able to write something like:
```python
t_start = observer.get_local_time(2015, 07, 28, 0, 30, 0) 
```
or even with strings:
```python
observer.get_local_time("2015-07-28 00:30") 
observer.get_local_time("07-28 00:30")        # assume current year
observer.get_local_time("19:20")                  # assume current day
```

I think if astroplan does not provide such a simple function, many users will be forced to write it over and over again.  Basically this applies to anyone who is planning in the timezone of the telescope and not UTC.

**Comment by bmorris3** [comment]
@ejeschke you propose porting the time parsing machinery that you used in [obsplan i.e. `get_date`](https://github.com/ejeschke/obsplan/blob/master/obsplan/entity.py#L233-L249) for this task?

**Comment by ejeschke** [comment]
Or at least using the idea.  i.e. use datetime.strptime or similar functionality that already knows how to parse date strings.

**Comment by bmorris3** [comment]
@eteq @adrn How do astropy folks feel about that? I could see concern that there could be confusion if the `astropy.time.Time` constructor and the dates that we use parsed different inputs.

**Comment by eteq** [comment]
I agree with @ejeschke that allowing an easier string  input would be good for local times.  But I do have the exact concern @bmorris3 noted about mixing various forms of constructors.

So here's something that might satisfy both.  Do something like this:
```python
if inputtime.__class__ is not datetime.datetime:
    apytime = astropy.time.Time(inputtime)
    inputtime = apytime.datetime
```
it's a bit counterintuitive, but that will mean that any sort of string that the `Time` constructor knows how to interpret will be converted to a UTC `Time` object, and then into a naive datetime, which you can then pass into the rest of the conversion logic.

So that allows the use of astropy's string-parsing machinery but still treating it as a datetime.  It also makes it easier to allow users to provide lists of strings - the same code above will then yield `inputtime` as an array of datetime objects, which you can just iterate over.

**Comment by bmorris3** [comment]
@astroplanners/astroplanners-contributors Last night, I was remote observing at APO from Seattle, and I used astroplan (!!!) which led me to some ideas about time zones.

For example, I began observing just after sunset, and after my undergrad asked when the sky would be fully dark, I went to use our convenience method: 
```python
from astroplan import Observer
from astropy.time import Time
apo = Observer.at_site("APO", timezone="US/Mountain")
twilight = apo.evening_astronomical(Time.now(), which='next')
print(twilight.iso)
# 2015-08-08 03:28:39.205
```
This is great, but what time is that in my local timezone? Well, I went to use the new methods that I wrote in #52, but I wrote those as converters for strings, so I had to do
```python
twilight_local_dt = apo.iso_utc_to_local_datetime(twilight.iso)
twilight_seattle_dt = twilight_local_dt.astimezone(pytz.timezone('US/Pacific'))
print(twilight_seattle_dt)
# 2015-08-07 20:28:38.725000-07:00
```
to get the Pacific equivalent of this time. I think this is a little cumbersome and messy. 

One thing I'd prefer to write, which breaks some conventions about how we've written `Observer` so far but I think it makes sense here (think "...practicality beats purity..."). How about a keyword argument for all methods that return times called `return_localized_datetime` which returns localized date times rather than astropy times? Then all of the above code could be reduced to: 
```python
from astroplan import Observer
from astropy.time import Time
apo = Observer.at_site("APO", timezone="US/Mountain")
twilight = apo.evening_astronomical(Time.now(), which='next', return_localized_datetime=True)
print(twilight.astimezone(pytz.timezone('US/Pacific')))
# 2015-08-07 20:28:38.725000-07:00
```
I don't think it's any less clear what's happening, and it allows us to continue to punt timezone handling to `pytz` in a transparent way.

**Comment by ejeschke** [comment]
I agree that returning time objects that are in astropy time format will be cumbersome for local timezone planning, since you are back to UTC and lost your timezone information.  I think this is why in `obsplan` everything generally returned `datetime` objects.

Hmm.  How about a setting in the observer object that would cause times to be returned as datetime timezone aware objects?  Would this complicate the code too much?  Since we are accepting datetime objects everywhere as input, it kind of makes sense that you could get that as output as well.

Wondering how this would affect array processing...is it efficient to convert an array of astropy `Time` objects to `datetime` objects?

**Comment by jberlanga** [comment]
@bmorris3: If you go with the keyword-in-all-methods approach, could you use a shorter keyword?  Maybe something like `local_datetime_out` or `local_time_out` or `return_local_time`?

**Comment by bmorris3** [comment]
@ejeschke I'd be OK with making an `Observer.__init__` kwarg like `return_local_datetime` that toggles the default behavior for all time-returning methods, and also making individual `return_local_datetime` methods for each time-returning method. 

Is this too complicated? I think for the users who care about timezones, this will make their code the cleanest.

**Comment by bmorris3** [comment]
@eteq @adrn I'm pinging you here for the text discussion we promised we'd have about [the above comment](https://github.com/astroplanners/astroplan/issues/46#issuecomment-128781142) on toggling datetime outputs from our time-computing methods.

**Comment by cdeil** [comment]
Status? Move to 0.2?

**Comment by bmorris3** [comment]
@cdeil :+1: for move to 0.2. A discussion still needs to be had about this.

**Comment by bmorris3** [comment]
I'm working on an astropy-based solution to this in astropy/astropy#4124.

**Comment by bmorris3** [comment]
@ejeschke – a solution to this was merged into astropy via astropy/astropy#4124 which will be released in astropy v1.1. Now you can convert `astropy.time.Time` objects output by astropy and convert them to localized datetimes like so: 

```python
>>> from astropy.time import Time
>>> from astroplan import Observer, FixedTarget
>>> import pytz

>>> vega = FixedTarget.from_name('Vega')
>>> obs = Observer.at_site("APO")
>>> tz = pytz.timezone('US/Mountain')
>>> obs.target_set_time(Time.now(), vega).to_datetime(tz)
datetime.datetime(2015, 10, 9, 2, 34, 55, 811498, tzinfo=<DstTzInfo 'US/Mountain' MDT-1 day, 18:00:00 DST>)
```

**Comment by ejeschke** [comment]
Thanks @bmorris3, it's certainly more succinct than before.   I still like the ideas discussed above (e.g. adding a kwarg preference or (better) adding a flag in the observer to return timezone aware times (ref. your seattle observing experience recounted above and follow on comments).

But maybe this can make it into a future release based on user feedback.

**Comment by bmorris3** [comment]
@ejeschke I've been using astroplan for 10 months since the last comment and think the current API is probably as intuitive as it's going to get when it comes to timezones. They're just so tricky. Do you still want to pursue an alternative API trick to manage timezones, or do you think we can close this issue now?

**Comment by ejeschke** [comment]
They are tricky.  I think you have to support it everywhere in the input and output API or you don't support it at all and make the user responsible.  That is what pyephem does (everything is assumed UT).  I assume from your comment above that is also the preferred approach for astroplan.

Given that astroplan is just riding on astropy `Time` objects, this probably makes sense. But it just means that the onus is on the user to manage timezones properly.  This just means that every observer using the package has to reinvent that wheel, with all the attendant complexity.

**Comment by bmorris3** [comment]
I agree that it is really annoying for the observer to deal with the time zone complexity. I agree because I am often that observer who is planning transit times using Julian dates, who then needs to propose for observing time in local time. I live in constant fear that I'm going to get it wrong. But every time I've tried writing a "smart" function that should know how to do those conversions, I wind up finding subtleties that lead to bugs bugs in it. Usually they're related to daylight savings time, which makes the problem 2^100 times harder. So I'm inclined to make users deal with that complexity complexly, because that's the only way to be sure that they'll see (and hopefully understand) how the sausage gets made.

Given all of that, I'm closing this issue. But if you can think of a way to make timezones easy @ejeschke, please tell me and you'll be my hero!

**Comment by ejeschke** [comment]
@bmorris3 , I noticed in the thread on `astropy-dev` regarding the "astroobs" package that he claims it properly supports local times and time zones:

> Hi Python-Astronomers,
> 
> I've been developing Astroobs (https://pypi.python.org/pypi/astroobs/) for my personal needs, and finally put it on "pip".
...
> In short, here are some cool features:
...
> * Proper handling of local times and time-zones, and of observatories at higher latitude than the arctic circles,

Just FYI; I think this will end up being a frequently requested enhancement for `astroplan`.
