### ISSUE TITLE
local_sidereal_time and target_meridian_transit_time disagree

### ISSUE THREAD

**Issue by jdtsmith** [astropy/astroplan#478]
For a class I’m having students use astropy+astroplan for a number of observing, coordinate and sun position calculations.  We came across something that is not quite clicking: the LST at a position on the Earth at a given time does not, according to astroplan’s `target_meridian_transit_time` actually transit at that time, but instead is several minutes off.  This makes a difference for example for computing the equation of time using the Sun as the target (which only varies +-15min or so).

```python
import astropy.units as u
from astropy.time import Time
from astropy.coordinates import EarthLocation,SkyCoord
from astropy.coordinates import get_sun
from astroplan import Observer
obs=Observer(location=EarthLocation.from_geodetic('-80°','45'))
time=Time('2020-10-15T15:00:00')
print('Time: ',time)
lst=obs.local_sidereal_time(time)
onmeridian=SkyCoord(lst,45*u.deg)
print('Position On Meridian: ',onmeridian.to_string('hmsdms'))
transit=obs.target_meridian_transit_time(time-5*u.min,onmeridian,which='next')
print('This transits at: ',transit.datetime)
```

```
Time:  2020-10-15T15:00:00.000
Position On Meridian:  11h18m23.7446s +45d00m00s
This transits at:  2020-10-15 15:03:05.567531
```

Thanks for this tool.

**Comment by bmorris3** [comment]
Hi! This point is addressed in the [FAQ section of the docs, read on here](https://astroplan.readthedocs.io/en/latest/faq/precision.html).

**Comment by jdtsmith** [comment]
Thanks.  I had read that and had as a result expected accuracy of order "seconds" as mentioned in this FAQ.  Here the offset is 1-4 minutes, which is quite large compared to some important effects like the Sun's equation of time.  I did find that if I significantly increased the number of grid points I get closer, but still ~1minute offset:

```python
transit=obs.target_meridian_transit_time(time-5*u.min,onmeridian,which='next',n_grid_points=5000)
This transits at:  2020-10-15 15:01:06.037542
```

I'll probably have them switch to PyEphem for this calculation, but it has a time/date format which isn't compatible with AstroPy, that becomes a bit confusing.

**Comment by StuartLittlefair** [comment]
This isn't actually for any reasons mentioned in the FAQ, but is due to the fine print in the equation LST = RA + HA.

The fine print is what coordinate system the RA is supposed to be in, and it's not ICRS, which is the default for SkyCoord. Instead, you would need to create a coordinate object in an Earth-centred, equatorial frame - i.e one where the equinox defines RA=0 and the equator defines Dec=0.

It is in this frame that LST = RA + HA applies. You can see this from the flowchart on p. 6 of the [sofa documentation](http://www.iausofa.org/publications/sofa_pn.pdf).

(I suspect this explanation will be too detailed for your students, but a simpler one is that the commonly used equation only works in an equatorial frame and astropy uses a different frame which has a slightly different origin for RA=0, hence the difference.)

There's no equatorial frame built into astropy, but we can hack together a transform from ICRS the the correct frame to see that the RA changes by about 1 minute....

```python
import astropy.units as u
from astropy.time import Time
from astropy import coordinates as coord
from astropy.coordinates.builtin_frames.utils import get_jd12
# rotates GCRS coordinate into equatorial coordinate
from astropy.coordinates.solar_system import _apparent_position_in_true_coordinates

time = Time('2020-10-15T15:00:00')
loc = coord.EarthLocation.from_geodetic('-80°', '45')
last = time.sidereal_time(kind='apparent', longitude=loc.lon)

# ICRS coordinate with RA=LST
coo = coord.SkyCoord(last, 45*u.deg)

# convert to GCRS
p, v = loc.get_gcrs_posvel(time)
gcrs_frame = coord.GCRS(obstime=time, obsgeoloc=p, obsgeovel=v)
gcrs_coo = coo.transform_to(gcrs_frame)

# get equatorial coord
equatorial_coo = _apparent_position_in_true_coordinates(gcrs_coo)

# RA diff in minutes
print( (equatorial_coo.ra - coo.ra).to_value(u.hourangle) * 60)
```

gives me a value of 1.1 minutes...

**Comment by jdtsmith** [comment]
> This isn't actually for any reasons mentioned in the FAQ, but is due to the fine print in the equation LST = RA + HA.

Very interesting, thanks for this. In fact the correction to the precessing+nutating pole also explains why changing the declination of the coordinate changes the LST offset by minutes.  I.e. if I had picked (say):

```python
dec=-84.420065*u.deg
onmeridian=SkyCoord(lst,dec)
````

I would have found:

```
This transits at:  2020-10-15 15:00:00
```

and been very impressed (as long as I didn't try any other positions on the meridian!).  FYI, your code predicts a difference between nominal frame RA and equatorial RA of just 0.13s for this position, so pretty great agreement!

I had assumed LST would encode "RA currently transiting at the given position, in the default coordinate frame".  Are there other uses of LST which make adopting this more "physical" frame valuable?  Put another way, you often see a statement like:

> Astronomers use local sidereal time because it corresponds to the coordinate right ascension of a celestial body that is presently on the local meridian.

But it never specifies _in what frame_ that coordinate right ascension is to be interpreted!  

And finally, if LST here is just a hard-to-interpret intermediary to figuring out at what time on a given day an object like the Sun transits, can you recommend an accurate `astropy`-based solution to that simpler problem?

**Comment by StuartLittlefair** [comment]
Well, ```astroplan.Observer.target_meridian_transit_time``` is simple and accurate. 

The LST = RA + HA equation is only ever used when precision is not needed I guess, so the question of which frame to use is not relevant.

But are you asking for the inverse problem, which is what RA transits at a  given time? In which case there is a clunky method, since astropy has the TEME frame, which precesses and nutates the equator, but only applies precession to the equinox. You can create a coordinate from LST in this frame, and it will be more accurate:

```python
# make a unit spherical representation of the ra, dec
srepr = coord.UnitSphericalRepresentation(last, 45*u.deg)

# make a TEME coordinate (takes cartesian input, since most often used with satellites)
teme = coord.TEME(srepr.to_cartesian(), obstime=time)

# find ICRS RA/Dec
coo = teme.transform_to(coord.ICRS())
```
