### ISSUE TITLE
cannot import name 'Observer' from 'astroplan'

### ISSUE THREAD

**Issue by alexfilothodoros** [astropy/astroplan#492]
Hello,

I have just installed astroplan via conda, on Big Sur.

I am trying to run this script https://astroplan.readthedocs.io/en/latest/tutorials/plots-3.py

but I get the error `ImportError: cannot import name 'Observer' from 'astroplan' `
astroplan.test() shows

`==================================================================== 84 passed, 7 warnings in 40.37s ====================================================================
Out[2]: <ExitCode.OK: 0>`

And ideas how this problem can be fixed?
Thanks

**Comment by Yash-10** [comment]
Hi,
I am still new here but running the script doesn't give me the error you have mentioned, although it does give me those warnings after running `astropy.test()`. Also, I am on Ubuntu and used pip for the installation.

But one thing I have noticed, which may not be related to this issue, is that `astroplan.observer` is a sub-module and is not a package itself. `Observer` is a class inside the `astroplan.observer` module. So maybe you can try to check the installed packages and submodules and use `observer.Observer` instead after importing observer?

The issue of [circular import dependency](https://stackoverflow.com/questions/1556387/circular-import-dependency-in-python) is seen quite common in such scenarios, which doesn't seem the case here since packages installed before `Observer` doesn't have Observer imported within them.

I thought these points might give some insight to the problem, kindly check if it helps.

Thanks.

**Comment by alexfilothodoros** [comment]
> But one thing I have noticed, which may not be related to this issue, is that `astroplan.observer` is a sub-module and is not a package itself. `Observer` is a class inside the `astroplan.observer` module. So maybe you can try to check the installed packages and submodules and use `observer.Observer` instead after importing observer?
Nice idea. This should get the job done.

Thanks mate :)
