### ISSUE TITLE
Remove deprecated astropy helper functions.

### ISSUE THREAD

**Issue by wtgee** [astropy/astroplan#553]
Need to remove this old function. `pytest` now warns by default but that seems different from an exception being raised. Not sure we really need exception raised since the warning is shown at end of test run.

              Failure is from astropy removing old code, which you should definitely fix, but unrelated to this PR.

_Originally posted by @pllim in https://github.com/astropy/astroplan/issues/552#issuecomment-1572878114_

**Comment by pllim** [comment]
No, I think it is a real error, since I actually removed the deprecated stuff from astropy today. It had been deprecated for a long time though, so maybe your CI was ignoring the deprecation before? 😅 

`ImportError: cannot import name 'enable_deprecations_as_exceptions' from 'astropy.tests.helper'`

See https://github.com/astropy/astropy/pull/14670
