### ISSUE TITLE
Does AltAz always fail below horizon?

### ISSUE THREAD

**Issue by bmorris3** [astropy/astroplan#60]
Question for @eteq / @adrn / @cdeil  – the [`AltAz` docs](https://astropy.readthedocs.org/en/stable/api/astropy.coordinates.AltAz.html?highlight=altaz) indicate: 

> Near and below altitudes of 0, [AltAz] can even give meaningless answers, and in this case transforming to AltAz and back to another frame can give highly discrepent results. For much better numerical stability, leaving the pressure at 0 (the default), disabling the refraction correction (yielding “topocentric” horizontal coordinates).

In the constraints module, I'm adding a constraint for finding the targets visible at night, i.e. `AtNight(max_solar_altitude=0*u.deg)`, and I will likely make subclasses of this constraint like `BetweenAstronomicalTwilights(max_solar_altitude=-18*u.deg)`, etc. In order to check if the sun is below those altitudes, I will be trying to use negative altitudes in just the way that the `AltAz` docs discourage. 

Are these altitudes predictably screwy in certain circumstances that we can avoid? For example, should we transform `get_sun` to `AltAz` with `pressure=0` always, to avoid the wonky computations?

**Comment by wtgee** [comment]
I have a similar use case of wanting AltAz below the horizon and actually
hadn't seen that note in the docs so I am glad you pointed it out.

We want to be able to point our mount directly down toward the ground (or
some target specific close to that) so I have been taking AltAz coordinates
that effectively just point down and transforming those into local HA/Dec.
The mount itself is capable of moving below the horizon but we were seeing,
well, wonky things.  I've just spending this week testing this and working
around.

But yes, I would like to be able to use an AltAz below the horizon if
possible as well, otherwise figure out a workaround.

Aloha,


On Wed, Aug 12, 2015 at 9:27 AM, Brett M. Morris <notifications@github.com>
wrote:

> Question for @eteq <https://github.com/eteq> / @adrn
> <https://github.com/adrn> / @cdeil <https://github.com/cdeil> – the AltAz
> docs
> <https://astropy.readthedocs.org/en/stable/api/astropy.coordinates.AltAz.html?highlight=altaz>
> indicate:
>
> Near and below altitudes of 0, [AltAz] can even give meaningless answers,
> and in this case transforming to AltAz and back to another frame can give
> highly discrepent results. For much better numerical stability, leaving the
> pressure at 0 (the default), disabling the refraction correction (yielding
> “topocentric” horizontal coordinates).
>
> In the constraints module, I'm adding a constraint for finding the targets
> visible at night, i.e. AtNight(max_solar_altitude=0*u.deg), and I will
> likely make subclasses of this constraint like
> BetweenAstronomicalTwilights(max_solar_altitude=-18*u.deg), etc. In order
> to check if the sun is below those altitudes, I will be trying to use
> negative altitudes in just the way that the AltAz docs discourage.
>
> Are these altitudes predictably screwy in certain circumstances that we
> can avoid? For example, should we transform get_sun to AltAz with
> pressure=0 always, to avoid the wonky computations?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/astroplanners/astroplan/issues/60>.
>



-- 
~Wilfred Tyler Gee

**Comment by cdeil** [comment]
@bmorris3 – I have no idea what kind of refraction correction Astropy applies for targets below the horizon.

Maybe you could just try and see what happens?
And if it doesn't work out of the box, come back with a concrete example where the default Astropy behaviour is no good here and we can discuss how to work around it.

Adding more tests, even for pathological input parameter cases, is always nice, to check that Astropy / astroplan react in a reasonable way (i.e. compute something sensible, or warn or error).
